### ISSUE TITLE
[BUG] 模块未生效

### ISSUE THREAD

**Issue by xxnuo** [wanghongenpin/Magisk-ProxyPinCA#1]
Android 13
MIUI 14.0.19
Magisk 26.1-delta(26100)
安装重启后在CA列表找不到ProxyPin证书，HTPPS抓包也不能正常使用
[magisk_log_2023-10-01T11.17.26.log](https://github.com/wanghongenpin/Magisk-ProxyPinCA/files/12776051/magisk_log_2023-10-01T11.17.26.log)

**Comment by wanghongenpin** [comment]
是不是和上面那个问题一样
#4

**Comment by xxnuo** [comment]
> 是不是和上面那个问题一样 #4

应该是的，我把这个先关了吧
